channels:
- conda-forge
dependencies:
- pip=20.2.4
- python=3.7
- poppler
- pip:
  - azure-cosmos
  - azureml-core
  - azureml-dataprep[fuse]
  - azureml-defaults
  - azureml-telemetry
  - azureml-train-restclients-hyperdrive
  - azureml-train-core
  - numpy
  - pdf2image